// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BugTracker.Persistance.Models;

#nullable disable

namespace BugTracker.Persistance
{
    public partial class BugtrackerContext : DbContext
    {
        public BugtrackerContext()
        {
        }

        public BugtrackerContext(DbContextOptions<BugtrackerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.CreatedDate).HasPrecision(4);

                entity.Property(e => e.LastLogin).HasPrecision(4);

                entity.Property(e => e.ProfilePicture).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}