// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BugTracker.Persistance.Models
{
    public partial class Groups
    {
        [Key]
        public int GroupId { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        public string Picture { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
    }
}